language: minimal
sudo: required
services:
  - docker
before_install:
  - docker pull debian:buster-slim
  - docker run --name build --rm --detach --interactive --mount type=bind,src=`pwd`,dst=/build debian:buster-slim /bin/sh
  - docker ps -a
  - docker exec -u root build apt-get -y update
  - docker exec -u root build apt-get --no-install-recommends -y install make gcc gcc-multilib gcc-mingw-w64 autoconf automake libtool pkg-config ca-certificates wget sed git-core golang-go moreutils zip go-dep
script:
  - travis_wait 40 docker exec build /build/.travis-make.sh make 3rdparty-all
  - docker exec build make -C /build unit-test
  - docker exec build make -C /build release
after_script:
  - docker exec build ls -l /build /build/_3rdparty/archive /build/_build/*
after_failure:
  - tail -n 1000 .travis-make.log
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: n4rvxOdbbvM12KHgEr2wuDQN+J06X+SMWb79LQDAQiUBAnxQvrg72ObhBdCIawnTI6/pTk23KtATQ9du1TVKDAYtOAKV1dTGBHBW8xPC0+/lbRLjJuaQRRjE2ZqQfR4q0FaSo3i/I6qwruUjTCWK98SSFkSBdEWxkbZA2kHZO3GStBrGgfs8kS6va3Tabp5qPwbSxlgjRnQoADEKw9wAAMHKOcJfWLku96Iv3JBLPvlGG45q3wxNFjE2OoL3tXagSOw99dZIusEColu7fv++73uxYWisG2dbxRERR2MDobLAgS8ewhmfWqHC/xjj2fbl6ZGnHjT+3QUfID6hfkUG2S+F6bl9imsjKfqqGUHVwGNUbW5RI/ASou+o9KrmE1Bd3FHDCnNbvwaiKJSWBJMvAJgTGXvg8FOpgh+KKGIoXx1wmIJtwYWeTPFhdqhtLhlE1mJkIwEOw+z0mKmC1uR/sAV8bIXSRy2y2gSIXbtSRR1CCw1DT2G1jdSNFdb2Kmyzh2wW+pDlbCXYJBA0gadvsGclhiqx6dzD96T+d3IWGgul1tFDFAJWPfRwAbtbsoQIjv+wQjnqCHCMQbIX0Tkrqu2k6KH7UyZ5T1YyNzQAeNSMdXZyYNO5dxfI5RpAVa6eJl7Ti5wvuNHdTJqnR66INt4YjR8CNk1U+P0pf9dB++A=
  file_glob: true
  file: spyre-*.zip
  on:
    repo: hillu/spyre
    tags: true
